import React, { useState, useEffect } from 'react';
import axios from 'axios';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import logo from '../assets/islamicStudieslogo.png'; 
function MyResult() {
  const [registrationNumber, setRegistrationNumber] = useState('');
  const [classRoll, setClassRoll] = useState('');
  const [result, setResult] = useState(null);
  const [error, setError] = useState('');


const handleDownloadPDF = async () => {
  const input = document.getElementById('result-section');
  const canvas = await html2canvas(input);
  const imgData = canvas.toDataURL('image/png');

  const pdf = new jsPDF('p', 'mm', 'a4');
  const pdfWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  // Header
  const logoImg = new Image();
  logoImg.src = logo;
  await new Promise((resolve) => { logoImg.onload = resolve; });

  // Top Logo
  pdf.addImage(logoImg, 'PNG', 15, 10, 20, 20);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(16);
  pdf.text('Department of Arabic & Islamic Studies', 105, 18, { align: 'center' });

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(12);
  pdf.text('Government City College, Chattogram', 105, 26, { align: 'center' });

  // Add grey background box around content area
  const contentX = 10;
  const contentY = 35;
  const contentWidth = pdfWidth - 20;

  pdf.setFillColor(245, 245, 245); // light grey
  pdf.rect(contentX, contentY, contentWidth, pageHeight - 60, 'F');

  // Add student result image (from HTML section)
  const imgProps = pdf.getImageProperties(imgData);
  const imgHeight = (imgProps.height * (contentWidth)) / imgProps.width;

  pdf.addImage(imgData, 'PNG', contentX + 5, contentY + 5, contentWidth - 10, imgHeight);

  // Footer
  pdf.setFontSize(10);
  pdf.setTextColor(100);
  pdf.text(
    '© Govt. City College, Ctg | Generated by Result Portal',
    pdfWidth / 2,
    pageHeight - 10,
    { align: 'center' }
  );

  // Save the PDF
  pdf.save('Student-Result.pdf');
};




  // 🔄 Load from localStorage if available
  useEffect(() => {
    const storedResult = localStorage.getItem('studentResult');
    if (storedResult) {
      setResult(JSON.parse(storedResult));
    }
  }, []);

  const handleSearch = async (e) => {
    e.preventDefault();
    setError('');
    setResult(null);

    if (!registrationNumber || !classRoll) {
      setError('Please provide both Registration Number and Class Roll');
      return;
    }

    try {
      const res = await axios.get('http://localhost:5000/api/results/result', {
        params: {
          registrationNumber,
          classRoll,
        },
      });

      setResult(res.data);
      localStorage.setItem('studentResult', JSON.stringify(res.data));
    } catch (err) {
      if (err.response && err.response.status === 404) {
        setError('Result not found for this Registration Number and Class Roll');
      } else {
        setError('Server error occurred');
      }
    }
  };

  const handleReset = () => {
    setRegistrationNumber('');
    setClassRoll('');
    setResult(null);
    setError('');
    localStorage.removeItem('studentResult');
  };

  return (
    <div className="max-w-3xl mx-auto px-4 pb-8 lg:pt-32 pt-24 font-english">
      {!result ? (
        <div className="bg-white shadow-md rounded-lg p-6">
          <h2 className="text-3xl font-bold text-gray-800 mb-6 text-center">🎓 Student Result Portal</h2>

          <form onSubmit={handleSearch} className="space-y-5">
            <div>
              <label className="block text-gray-700 font-medium mb-2">Registration Number</label>
              <input
                type="text"
                value={registrationNumber}
                onChange={(e) => setRegistrationNumber(e.target.value)}
                className="w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="e.g. 123456"
              />
            </div>

            <div>
              <label className="block text-gray-700 font-medium mb-2">Class Roll</label>
              <input
                type="text"
                value={classRoll}
                onChange={(e) => setClassRoll(e.target.value)}
                className="w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="e.g. 10"
              />
            </div>

            <button
              type="submit"
              className="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 rounded-md transition duration-200"
            >
              🔍 Search Result
            </button>

            {error && <p className="text-red-600 text-sm mt-2">{error}</p>}
          </form>
        </div>
      ) : (
        <div id="result-section" className="bg-white shadow-lg rounded-lg p-6 max-w-3xl mx-auto border border-gray-300">
          <h2 className="text-2xl font-bold text-blue-700 mb-4 text-center">📄 Student Result</h2>

       <div id="result-section">

              <div className="grid sm:grid-cols-2 gap-4 mb-6">
            <p><strong>Name:</strong> {result.studentName}</p>
            <p><strong>Reg. No:</strong> {result.registrationNumber}</p>
            <p><strong>Class Roll:</strong> {result.classRoll}</p>
            <p><strong>Department:</strong> {result.department}</p>
            <p><strong>Year:</strong> {result.year}</p>
            <p><strong>Exam Type:</strong> {result.examType}</p>
          </div>

          <div>
            <h3 className="text-xl font-semibold mb-2">📚 Subjects & Marks</h3>
            <div className="overflow-x-auto">
              <table className="w-full text-left border border-gray-300">
                <thead className="bg-gray-100">
                  <tr>
                    <th className="border px-3 py-2">Subject Code</th>
                    <th className="border px-3 py-2">Subject</th>
                    <th className="border px-3 py-2">Marks</th>
                    <th className="border px-3 py-2">GPA</th>
                  </tr>
                </thead>
                <tbody>
                  {result.results?.map((sub, idx) => (
                    <tr key={idx}>
                      <td className="border px-3 py-2">{sub.subjectCode}</td>
                      <td className="border px-3 py-2">{sub.subject}</td>
                      <td className="border px-3 py-2">{sub.marks}</td>
                      <td className="border px-3 py-2">{(sub.gpa || 0).toFixed(2)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          <div className="mt-4 space-y-1">
            <p><strong>📊 Total Marks:</strong> {result.totalMarks}</p>
            <p><strong>🎯 Average CGPA:</strong> {(result.averageGpa || 0).toFixed(2)} out of 4.00</p>
            <p><strong>🏅 Grade:</strong> {result.averageGrade}</p>
           </div>

       </div>
             

            <button
              onClick={handleDownloadPDF}
              className="mt-4 w-full bg-green-600 hover:bg-green-700 text-white font-semibold py-2 rounded-md transition duration-200"
            >
              📥 Download PDF Marksheet
            </button>


          <button
            onClick={handleReset}
            className="mt-6 w-full bg-gray-200 hover:bg-gray-300 text-gray-800 font-semibold py-2 rounded-md transition duration-200"
          >
            🔄 Search Another Result
          </button>
        </div>
      )}
    </div>
  );
}

export default MyResult;
